// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LoadImageController from "./load_image_controller"
application.register("load-image", LoadImageController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)